# Generated by Django 4.0.1 on 2022-01-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('number', models.IntegerField(unique=True)),
                ('price', models.IntegerField(unique=True)),
                ('presence', models.BooleanField(default=False)),
            ],
        ),
    ]
